"""
sales_event_generator.py

Advanced-level sales event generator for the Sari-Sari Store Simulator.

Creates grocery-wide promotions that span date ranges and affect specific
product categories. Events cause visible demand spikes in the transaction
data generated by five_year_generator.py via demand_multiplier.

Categories match the real inventory.csv data:
    Beverage, Food, Snack, Personal Care, Household

Each event record contains:
    event_id          : Unique identifier (e.g. EVT-2022-001)
    event_name        : Human-readable promo label
    start_date        : First day of the promotion
    end_date          : Last day of the promotion
    discount_rate     : Fractional discount offered (e.g. 0.15 = 15% off)
    affected_category : Which product category gets the promo
    demand_multiplier : How much demand increases during the event

Philippine sari-sari store context used to design events:
- Summer (Apr-Jun): beverage and snack peaks
- Fiesta months (May-Jun): food and beverage spending rises
- Back-to-school (Jun-Jul): personal care and household demand rises
- Ber months (Sep-Dec): gradual Christmas build-up across all categories
- Christmas season (Nov-Dec): highest spending period of the year

Output files:
    data/processed/advanced/sales_events.csv  (aggregated five-year)
    data/processed/advanced/year_YYYY/month_MM/sales_events.csv (per month)
    SQLite table: advanced_sales_events
"""

from pathlib import Path
import pandas as pd
import numpy as np
from datetime import date, timedelta
import calendar

from sqlalchemy import create_engine

try:
    from src.advanced.five_year_generator import START_YEAR, END_YEAR
except ModuleNotFoundError:
    START_YEAR = 2022
    END_YEAR = 2026


# ---------------------------------------------------------------------------
# Event templates
# Each tuple: (month, start_day, duration_days, name, category, discount_rate)
# These recur every year with slight date jitter (±2 days) for realism.
# ---------------------------------------------------------------------------

EVENT_TEMPLATES = [
    # January
    (1,  10,  7, "New Year Clearance Sale",           "Food",          0.10),
    (1,  20,  5, "January Beverage Promo",             "Beverage",      0.08),

    # February
    (2,  10,  5, "Valentine's Day Snack Promo",        "Snack",         0.12),

    # March
    (3,  20,  6, "Holy Week Canned Food Sale",         "Food",          0.15),

    # April
    (4,   1,  5, "Summer Kickoff Beverage Sale",       "Beverage",      0.18),
    (4,  15,  7, "Summer Snack Festival",              "Snack",         0.15),

    # May
    (5,   1, 10, "Fiesta Season Food Sale",            "Food",          0.12),
    (5,  15,  5, "Household Essentials Promo",         "Household",     0.10),

    # June
    (6,   1,  7, "Back-to-School Personal Care Sale",  "Personal Care", 0.15),
    (6,  15,  7, "Midsummer Beverage Blowout",         "Beverage",      0.20),

    # July
    (7,   1,  5, "Back-to-School Household Promo",     "Household",     0.12),
    (7,  20,  6, "Rainy Day Food Comfort Sale",        "Food",          0.10),

    # August
    (8,  10,  5, "National Heroes Day Snack Promo",    "Snack",         0.10),
    (8,  20,  5, "Beverage Restock Promo",             "Beverage",      0.08),

    # September
    (9,   1,  7, "Ber Month Kickoff Beverage Sale",    "Beverage",      0.12),
    (9,  20,  5, "Personal Care Monthly Promo",        "Personal Care", 0.10),

    # October
    (10,  1, 10, "October Fiesta Food Sale",           "Food",          0.15),
    (10, 20,  5, "Pre-Holiday Household Sale",         "Household",     0.12),

    # November
    (11,  1, 14, "Christmas Season Kickoff Beverage",  "Beverage",      0.15),
    (11, 15,  7, "Holiday Snack Bonanza",              "Snack",         0.20),

    # December
    (12,  1, 10, "Christmas Food Promo",               "Food",          0.18),
    (12, 15, 16, "Christmas and New Year Grand Sale",  "Beverage",      0.20),
]

# Demand elasticity: units of demand increase per unit of discount.
# At 0.15 discount rate and elasticity 3.0 → 1 + (0.15 * 3.0) = 1.45x demand.
DEMAND_ELASTICITY = 3.0


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _demand_multiplier(discount_rate: float) -> float:
    """
    Estimate demand increase from a given discount rate.

    Uses a linear elasticity model:
        multiplier = 1 + (discount_rate * DEMAND_ELASTICITY)

    Parameters
    ----------
    discount_rate : float
        Fractional discount (e.g. 0.15 for 15% off).

    Returns
    -------
    float
        Demand multiplier (e.g. 1.45 at 15% discount).
    """
    return round(1.0 + (discount_rate * DEMAND_ELASTICITY), 4)


def _safe_date(year: int, month: int, day: int) -> date:
    """
    Return a valid date, clamping day to the last valid day of the month.
    """
    last_day = calendar.monthrange(year, month)[1]
    return date(year, month, min(day, last_day))


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def generate_sales_events(
    start_year: int = START_YEAR,
    end_year: int = END_YEAR,
    random_seed: int = 42,
) -> pd.DataFrame:
    """
    Generate all sales events for the five-year simulation period.

    Uses EVENT_TEMPLATES to create recurring annual promotions.
    Each event gets ±2-day date jitter to simulate real-world variation.

    Parameters
    ----------
    start_year : int
        First year of simulation.
    end_year : int
        Last year of simulation.
    random_seed : int
        Seed for reproducible date jitter.

    Returns
    -------
    pd.DataFrame
        Sales events with columns:
        event_id, event_name, start_date, end_date,
        discount_rate, affected_category, demand_multiplier
    """
    rng = np.random.default_rng(random_seed)
    rows = []
    counter = 1

    for year in range(start_year, end_year + 1):
        for (
            month,
            start_day,
            duration,
            name,
            category,
            discount_rate,
        ) in EVENT_TEMPLATES:

            jitter = int(rng.integers(-2, 3))
            actual_start_day = max(1, start_day + jitter)

            start_dt = _safe_date(year, month, actual_start_day)
            end_dt = start_dt + timedelta(days=duration - 1)

            # Cap at Dec 31 of the same year
            if end_dt > date(year, 12, 31):
                end_dt = date(year, 12, 31)

            rows.append({
                "event_id":          f"EVT-{year}-{counter:03d}",
                "event_name":        name,
                "start_date":        start_dt,
                "end_date":          end_dt,
                "discount_rate":     discount_rate,
                "affected_category": category,
                "demand_multiplier": _demand_multiplier(discount_rate),
            })

            counter += 1

    events = pd.DataFrame(rows, columns=[
        "event_id",
        "event_name",
        "start_date",
        "end_date",
        "discount_rate",
        "affected_category",
        "demand_multiplier",
    ])

    events["start_date"] = pd.to_datetime(events["start_date"])
    events["end_date"]   = pd.to_datetime(events["end_date"])

    return events


def get_events_for_month(
    sales_events: pd.DataFrame,
    year: int,
    month: int,
) -> pd.DataFrame:
    """
    Return the subset of events that overlap with a given month.

    An event overlaps if any part of its date range falls within the month.

    Parameters
    ----------
    sales_events : pd.DataFrame
        Full sales events DataFrame from generate_sales_events().
    year : int
        Target year.
    month : int
        Target month (1-12).

    Returns
    -------
    pd.DataFrame
        Events active during the target month.
    """
    last_day = calendar.monthrange(year, month)[1]
    month_start = pd.Timestamp(date(year, month, 1))
    month_end   = pd.Timestamp(date(year, month, last_day))

    mask = (
        (sales_events["start_date"] <= month_end)
        & (sales_events["end_date"] >= month_start)
    )
    return sales_events[mask].copy().reset_index(drop=True)


# ---------------------------------------------------------------------------
# Save helpers
# ---------------------------------------------------------------------------

def save_sales_events_csv(
    sales_events: pd.DataFrame,
    output_base_folder: str | Path,
) -> Path:
    """
    Save the full five-year sales events table to the advanced root folder.

    Parameters
    ----------
    sales_events : pd.DataFrame
        Full events DataFrame.
    output_base_folder : str or Path
        Root advanced output folder (data/processed/advanced).

    Returns
    -------
    Path
        Path of the saved CSV.
    """
    folder = Path(output_base_folder)
    folder.mkdir(parents=True, exist_ok=True)

    path = folder / "sales_events.csv"
    sales_events.to_csv(path, index=False)
    return path


def save_monthly_sales_events_csv(
    sales_events: pd.DataFrame,
    year: int,
    month: int,
    output_base_folder: str | Path,
) -> Path:
    """
    Save the sales events active in one month to its year/month folder.

    Parameters
    ----------
    sales_events : pd.DataFrame
        Full events DataFrame (filtered internally to the target month).
    year : int
        Target year.
    month : int
        Target month (1-12).
    output_base_folder : str or Path
        Root advanced output folder.

    Returns
    -------
    Path
        Path of the saved CSV.
    """
    monthly = get_events_for_month(sales_events, year, month)

    folder = (
        Path(output_base_folder) / f"year_{year}" / f"month_{month:02d}"
    )
    folder.mkdir(parents=True, exist_ok=True)

    path = folder / "sales_events.csv"
    monthly.to_csv(path, index=False)
    return path


def save_sales_events_to_sqlite(
    sales_events: pd.DataFrame,
    sqlite_db_path: str | Path,
) -> None:
    """
    Save the full sales events DataFrame to SQLite.

    Table name: advanced_sales_events

    Parameters
    ----------
    sales_events : pd.DataFrame
        Full events DataFrame.
    sqlite_db_path : str or Path
        Path to the SQLite database.
    """
    sqlite_db_path = Path(sqlite_db_path)
    sqlite_db_path.parent.mkdir(parents=True, exist_ok=True)

    engine = create_engine(f"sqlite:///{sqlite_db_path}")

    sales_events.to_sql(
        name="advanced_sales_events",
        con=engine,
        if_exists="replace",
        index=False,
    )

    print(f"SQLite table saved    : advanced_sales_events → {sqlite_db_path}")


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def run_sales_event_generator(
    output_base_folder: str | Path = "data/processed/advanced",
    sqlite_db_path: str | Path = "src/database/sari_sari_store.db",
    random_seed: int = 42,
    save_csv: bool = True,
    save_sqlite: bool = True,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Run the full sales event generation workflow.

    Generates five years of promotional events, prints a summary,
    saves to CSV and SQLite, and returns the full events DataFrame
    for use downstream in five_year_generator.py.

    Parameters
    ----------
    output_base_folder : str or Path
        Root advanced output folder.
    sqlite_db_path : str or Path
        Path to the SQLite database.
    random_seed : int
        Seed for reproducible date jitter.
    save_csv : bool
        Whether to save the aggregated events CSV.
    save_sqlite : bool
        Whether to save to SQLite.
    verbose : bool
        Whether to print a summary to the console.

    Returns
    -------
    pd.DataFrame
        Full five-year sales events DataFrame.
    """
    sales_events = generate_sales_events(
        start_year=START_YEAR,
        end_year=END_YEAR,
        random_seed=random_seed,
    )

    if verbose:
        print("\n" + "=" * 72)
        print("ADVANCED GOAL: SALES EVENT GENERATOR")
        print("=" * 72)
        print(f"Total events generated : {len(sales_events)}")
        print(f"Average discount rate  : {sales_events['discount_rate'].mean():.1%}")
        print(f"Average demand boost   : {sales_events['demand_multiplier'].mean():.2f}x")
        print("\nEvents by category:")
        by_cat = (
            sales_events.groupby("affected_category")
            .size()
            .sort_values(ascending=False)
            .reset_index(name="count")
        )
        for _, row in by_cat.iterrows():
            print(f"  {row['affected_category']:<20} : {row['count']} events")
        print("=" * 72)

    if save_csv:
        path = save_sales_events_csv(sales_events, output_base_folder)
        print(f"\nAggregated CSV saved  : {path}")

    if save_sqlite:
        save_sales_events_to_sqlite(sales_events, sqlite_db_path)

    return sales_events


if __name__ == "__main__":
    run_sales_event_generator()
